### PR TITLE
fixed #53, checksum mismatch

### LINKED ISSUE #53: checksum address mismatch
native-signer incorrectly caluclates checksum

### PR DESCRIPTION
**Pull request by debris**
checksum's keccak hashes addresses as strings, not as bytes

### CODE REVIEW

**Comment by tomusdrw** [comment]
Can you add couple of tests to prove the correctness? (Preferably the same vectors as in parity)

**Comment by debris** [comment]
I would like to, but native modules are not available in test environment :/ I will create an issue to set up this

**Comment by tomusdrw** [comment]
You can mock native modules or separate wallet derivation from checksum encoding.

**Comment by debris** [comment]
I've added 2 tests. They are not exactly the same as parity's (parity has only 1 test for it), but I've verified those results agains parity

**Pull request merged**
